-- Catalog seed only; runtime data is always read from PostgreSQL.
begin;
insert into public.products(id,slug,name,description,category,brand,price,original_price,image_url,images,variants,tagline,features,rating,review_count,stock) values
('airpods-max','airpods-max','Apple AirPods Max','Over-ear wireless headphones with a comfortable knit canopy and rich, room-filling sound.','Electronics','Apple','399','549','/products/airpods-max-0.webp','["/products/airpods-max-0.webp"]','["Silver"]','Immersive listening. Beautifully simple.','["Active noise cancellation","Up to 20 hours of listening","Comfortable over-ear cushions"]','4.8','1248','20'),
('airpods','airpods','Apple AirPods with charging case','Lightweight wireless earbuds with an easy-to-carry charging case.','Electronics','Apple','99','129','/products/airpods-0.webp','["/products/airpods-0.webp","/products/airpods-1.webp","/products/airpods-2.webp"]','["White"]','Your everyday soundtrack.','["Wireless Bluetooth connection","Pocket-sized charging case","Built-in microphone"]','4.6','862','21'),
('macbook','macbook','Apple MacBook Pro 14-inch','A capable 14-inch laptop for creative projects, study, and everyday productivity.','Electronics','Apple','1299','1499','/products/macbook-0.webp','["/products/macbook-0.webp","/products/macbook-1.webp","/products/macbook-2.webp"]','["Space Grey"]','Make room for your next big idea.','["14-inch display","Backlit keyboard","USB-C connectivity"]','4.9','2301','22'),
('apple-watch','apple-watch','Apple Watch, gold aluminum','A comfortable everyday smartwatch for activity, notifications, and staying connected.','Electronics','Apple','179','229','/products/apple-watch-0.webp','["/products/apple-watch-0.webp","/products/apple-watch-1.webp","/products/apple-watch-2.webp"]','["Gold"]','A little more connected.','["Activity tracking","Comfortable sport band","Clear touch display"]','4.7','416','23'),
('homepod','homepod','Apple HomePod mini','A compact home speaker that brings music into your favorite spaces.','Electronics','Apple','79','99','/products/homepod-0.webp','["/products/homepod-0.webp"]','["Space Grey"]','Small speaker. Big personality.','["Compact spherical design","Room-filling audio","Simple touch controls"]','4.5','975','24'),
('wireless-charger','wireless-charger','Wireless charging mat','A clean charging surface for your compatible everyday devices.','Electronics','Apple','29','39','/products/wireless-charger-0.webp','["/products/wireless-charger-0.webp"]','["White"]','Less cable clutter.','["Slim desktop design","Wireless charging","Non-slip base"]','4.8','328','25'),
('table-lamp','table-lamp','Classic brass table lamp','Warm up a desk, bedside table, or reading nook with a classic brass-tone lamp and fabric shade.','Home','ShopSwift Home','39','55','/products/table-lamp-0.webp','["/products/table-lamp-0.webp"]','["Brass"]','A brighter little corner.','["Soft ambient light","Compact footprint","Easy on/off switch"]','4.6','1248','26'),
('plant-pot','plant-pot','Botanical ceramic planter','An easy finishing touch for shelves, windowsills, and sunny corners.','Home','ShopSwift Home','24','32','/products/plant-pot-0.webp','["/products/plant-pot-0.webp","/products/plant-pot-1.webp","/products/plant-pot-2.webp"]','["Natural"]','Bring the outside in.','["Decorative planter","Easy-care design","Perfect for a shelf or desk"]','4.9','862','27'),
('blender','blender','Everyday countertop blender','Blend fruit, smoothies, and kitchen favorites with this countertop essential.','Home','ShopSwift Home','49','69','/products/blender-0.webp','["/products/blender-0.webp","/products/blender-1.webp","/products/blender-2.webp"]','["Black"]','Good mornings start here.','["Easy-to-use controls","Removable blending jar","Compact kitchen footprint"]','4.7','2301','28'),
('travel-cup','travel-cup','Everyday black aluminum cup','A lightweight reusable cup for coffee breaks and everyday refreshments.','Home','ShopSwift Home','14','19','/products/travel-cup-0.webp','["/products/travel-cup-0.webp","/products/travel-cup-1.webp"]','["Black"]','Your favorite daily ritual.','["Lightweight aluminum","Reusable design","Easy-grip handle"]','4.5','416','29'),
('puma-trainers','puma-trainers','Puma Future Rider trainers','Everyday sneakers with a retro-inspired profile and an easy, comfortable fit.','Fashion','Puma','64','85','/products/puma-trainers-0.webp','["/products/puma-trainers-0.webp","/products/puma-trainers-1.webp","/products/puma-trainers-2.webp"]','["US 8","US 9","US 10","US 11"]','Go a little further.','["Cushioned sole","Lace-up closure","Casual everyday styling"]','4.8','975','30'),
('casual-shirt','casual-shirt','Everyday checked cotton shirt','An easygoing shirt that moves from a casual workday to weekend plans.','Fashion','Fashion Trends','29','42','/products/casual-shirt-0.webp','["/products/casual-shirt-0.webp","/products/casual-shirt-1.webp","/products/casual-shirt-2.webp"]','["S","M","L","XL"]','Your new everyday favorite.','["Classic button closure","Comfortable regular fit","Machine washable"]','4.6','328','31'),
('daypack','daypack','Faux leather everyday backpack','A clean, versatile backpack with room for your daily essentials.','Fashion','Urban Chic','42','59','/products/daypack-0.webp','["/products/daypack-0.webp","/products/daypack-1.webp","/products/daypack-2.webp"]','["White"]','Take the day with you.','["Adjustable shoulder straps","Secure zip closure","Easy-clean faux leather"]','4.9','1248','32'),
('leather-watch','leather-watch','Classic brown leather watch','A timeless everyday watch with a leather strap and an easy-to-read dial.','Fashion','Fashion Timepieces','59','79','/products/leather-watch-0.webp','["/products/leather-watch-0.webp","/products/leather-watch-1.webp","/products/leather-watch-2.webp"]','["Brown"]','Right on time.','["Adjustable leather strap","Classic analog dial","Everyday lightweight feel"]','4.7','862','33'),
('tennis-racket','tennis-racket','Court Club tennis racket','A comfortable recreational racket for your next friendly match.','Fitness','ShopSwift Home','39','55','/products/tennis-racket-0.webp','["/products/tennis-racket-0.webp"]','["Standard"]','Make time to play.','["Comfortable wrapped grip","Recreational all-court design","Lightweight frame"]','4.5','2301','34'),
('basketball','basketball','All Court basketball','A durable basketball for pick-up games, practice, and weekends outdoors.','Fitness','ShopSwift Home','24','32','/products/basketball-0.webp','["/products/basketball-0.webp"]','["Size 7"]','A little friendly competition.','["Textured grip","Indoor and outdoor play","Standard size 7"]','4.8','416','35'),
('controller','controller','Wireless game controller','A comfortable wireless controller for relaxed couch gaming and long weekend sessions.','Gaming','Studio','49','69','/products/controller-0.jpg','["/products/controller-0.jpg"]','["White"]','Ready, player one.','["Ergonomic grip","Responsive controls","USB-C charging"]','4.5','184','24'),
('keyboard','keyboard','Compact mechanical keyboard','A compact desktop keyboard with satisfying tactile feedback and a clean layout.','Gaming','Studio','69','99','/products/keyboard-0.jpg','["/products/keyboard-0.jpg"]','["Standard"]','Find your flow.','["Compact desktop footprint","Mechanical switches","USB connection"]','4.6','357','24'),
('small-habits','small-habits','Small Habits, Better Days','A fictional ShopSwift edition exploring thoughtful routines and small daily changes. An original demo book.','Books','ShopSwift Press','16','22','/products/small-habits.svg','["/products/small-habits.svg"]','["Paperback"]','A good day starts small.','["Original demo edition","Paperback format","240 pages"]','4.7','530','24'),
('creative-life','creative-life','The Creative Life','An original demo book about curiosity, finding inspiration, and making space for creative work.','Books','ShopSwift Press','19','26','/products/creative-life.svg','["/products/creative-life.svg"]','["Hardcover"]','Make something that matters.','["Original demo edition","Hardcover format","192 pages"]','4.8','703','24')
on conflict(id) do nothing;
commit;
