'use client';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Check, Eye, EyeOff, Sparkles, ShieldCheck, LoaderCircle } from 'lucide-react';
import { useStore } from './store';
export function AuthForm(){
 const store=useStore();const router=useRouter();const params=useSearchParams();const requested=params.get('next');const next=requested&&['/checkout','/orders','/account'].includes(requested)?requested:'/account';
 const [signup,setSignup]=useState(false);const [email,setEmail]=useState('');const [name,setName]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(signup&&name.trim().length<2){setError('Please enter a name with at least two characters.');return;}setBusy(true);try{if(signup)await store.signup(name,email,password);else await store.login(email,password);router.push(next);}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please try again.');}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-story"><span className="hero-kicker">A LITTLE BETTER, EVERY DAY</span><h1>Your kind of finds.<br/>Your kind of store.</h1><p>All the everyday things you love,<br/>together in one happy place.</p><div className="auth-illustration"><span><ShoppingBagIllustration/></span></div><ul><li><Check size={17}/>A cart that remembers your favorites</li><li><Check size={17}/>An easy checkout, from start to finish</li><li><Check size={17}/>Your good finds, all in one place</li></ul></div><section className="auth-form-panel"><span className="eyebrow">WELCOME TO SHOPSWIFT</span><h2>{signup?'A fresh start. Great finds.':'Good to see you.'}</h2><p>{signup?'Create a demo account and make yourself at home.':'Sign in to pick up where you left off.'}</p><button className="button primary full" disabled={!store.ready||busy} onClick={()=>{store.demoLogin();router.push(next);}}><Sparkles size={17}/>Continue as demo user<ArrowRight size={16}/></button><div className="or-divider"><span/>or {signup?'create an account':'sign in with email'}<span/></div><form onSubmit={submit}>{signup&&<div className="field"><label htmlFor="name">Your name</label><input id="name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={60} placeholder="Alex Morgan"/></div>}<div className="field"><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={120} placeholder="you@example.com"/></div><div className="field"><label htmlFor="password">Password</label><div className="password-input"><input id="password" type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={signup?6:1} maxLength={100} placeholder={signup?'At least 6 characters':'Enter your demo password'}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button dark full" disabled={busy||!store.ready}>{busy?<LoaderCircle className="spin" size={17}/>:null}{signup?'Create demo account':'Sign in'}<ArrowRight size={16}/></button></form><p className="auth-switch">{signup?'Already feel at home?':'New around here?'} <button onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Sign in':'Create an account'}</button></p><div className="demo-credentials"><ShieldCheck size={19}/><div><b>Just exploring? You’re in the right place.</b><p>Use <code>demo@shopswift.com</code> / <code>demo123</code>, or the demo button above. Accounts stay in this browser. Please use a made-up password.</p></div></div><Link className="text-link" href="/search">Keep browsing without signing in<ArrowRight size={14}/></Link></section></div>;
}
function ShoppingBagIllustration(){return <svg viewBox="0 0 240 200" aria-hidden="true"><circle cx="120" cy="100" r="91" fill="#dfe6d4"/><path d="m66 69-10 114h126L170 69Z" fill="#efb757"/><path d="M93 78V56a26 26 0 0 1 52 0v22" fill="none" stroke="#254635" strokeWidth="6" strokeLinecap="round"/><path d="m129 98-24 34h18l-5 27 28-37h-21Z" fill="#244937"/><path d="m44 46 3 9 9 3-9 3-3 9-3-9-9-3 9-3Zm143 58 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z" fill="#a6b297"/></svg>;}
